### PR TITLE
Update to airbnb 13.0.0

### PR DESCRIPTION
**Pull request by justin808**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/style-guide-javascript/18)

### CODE REVIEW

**Comment by justin808** [comment]
@alexfedoseev @robwise What shall we do about this one? merge and ship it?

This is implemented in the https://github.com/shakacode/react-webpack-rails-tutorial and https://github.com/shakacode/bootstrap-loader/

**Comment by robwise** [comment]
That's fine with me

**Comment by alex35mil** [comment]
LGTM, except few moments, that I discovered in FNG after update (see diff for eslint config in PR). Not critical tho, can be considered for the next update.

**Comment by justin808** [comment]
> So you want to remove the exception to the airbnb rule on the `_` for unused params?
> and then ship?

@robwise if you agree, we ship.

**Comment by robwise** [comment]
I prefer the `_` style, but I don't feel strongly about it so whatever's easiest for the team is good with me

**Comment by justin808** [comment]
@alexfedoseev @robwise How about the case of wanting to provide say a 3rd parameter when only 2 are used, just to document that the function would receive 3 params? Putting the underscore just says "ignore" which is what is wanted. An example is the passing of `railsContext` in React on Rails. Any harm with leaving in the style of allowing _ for unused params? or should the case of passing in an extra, unused param be either just documented that this would be available or with a lint ignore. 

So why document this? It's not always obvious what params a callback will pass.

In any case, I'd like to ship this soon!

**Comment by justin808** [comment]
@alexfedoseev @robwise we'll deal with overrides in the next PR.

**Comment by justin808** [comment]
13.2.0 shipped!

**Pull request merged**
